const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
const RESPONSE_COUNTRIES = 'RESPONSE_COUNTRIES';
const IS_COUNTRIES_LOADING = 'IS_COUNTRIES_LOADING';

export { REQUEST_COUNTRIES, RESPONSE_COUNTRIES, IS_COUNTRIES_LOADING };
